### ISSUE TITLE
Add secretSpec

### ISSUE THREAD

**Issue by jerry153fish** [jerry153fish/cloudformation-secrets#4]
```
apiVersion: cfn.jerry153fish.com/v1alpha1
kind: Secrets
metadata:
  name: secrets-sample
spec:
  # Add fields here
  secretName: test 
  cfn:
  - key: test1
    stackName: xxx
    outputKey: xxx
    type: xxx
```
